version: '3'

services:
  mongo:
    image: mongo
    container_name: logProtoConsumerMongo
    restart: always
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: logProtoConsumer
      MONGO_NON_ROOT_USERNAME: log
      MONGO_NON_ROOT_PASSWORD: proto
    ports:
      - 27018:27017
    volumes: 
      - ./data/db:/data/db
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: logProtoConsumerMongoExpress
    restart: always
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_PORT=27018
      - ME_CONFIG_MONGODB_SERVER=mongo
      - VCAP_APP_PORT=8081

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: nodejs
    container_name: logProtoConsumerApi
    restart: unless-stopped
    environment:
      - PORT=3003
    ports:
      - 3003:3003
    volumes:
      - .:/api
    depends_on:
      - mongo
    command: node app.js
